# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Hans Liljestrand <hans@liljestrand.dev>
"""Bash launcher template used by :mod:`pyishlib.launchers`."""

TEMPLATE = """\
#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Generated by pyishlib.launchers. Do not edit.
# Regenerate with: ishfiles apply  or  python -m pyishlib.launchers install
# Tool:   __TOOL_NAME__
# Module: __TOOL_MODULE__

set -eu

: "${ISHLIB_SRC:=__SOURCE_DIR__}"

_pick_python() {
    if [ -n "${ISHLIB_PYTHON:-}" ] && [ -x "${ISHLIB_PYTHON}" ]; then
        printf '%s' "$ISHLIB_PYTHON"; return
    fi
    if command -v pyenv >/dev/null 2>&1; then
        _v=$(pyenv global 2>/dev/null | head -n1 || true)
        if [ -n "$_v" ] && [ "$_v" != "system" ]; then
            _p="$(pyenv root)/versions/$_v/bin/python3"
            [ -x "$_p" ] && { printf '%s' "$_p"; return; }
        fi
    fi
    [ -x /usr/bin/python3 ] && { printf '%s' /usr/bin/python3; return; }
    command -v python3
}

py=$(_pick_python) || { echo "error: no python3 interpreter found" >&2; exit 1; }

unset PYTHONHOME VIRTUAL_ENV
export PYTHONNOUSERSITE=1
export PYTHONPATH="${ISHLIB_SRC}${PYTHONPATH:+:$PYTHONPATH}"

exec "$py" -m __TOOL_MODULE__ "$@"
"""
