#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Hans Liljestrand <hans@liljestrand.dev>
"""Generate docs/pyishlib/ from pyishlib docstrings using griffe."""

import os
import re

import griffe

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT_DIR, "src")
OUTPUT_DIR = os.path.join(ROOT_DIR, "docs", "pyishlib")

GENERATED_NOTICE = (
    "> **Note:** This file is auto-generated by"
    " `scripts/build_pydocs.py`. Do not edit directly."
)


def clean_rst(text):
    """Convert rST inline markup to markdown."""
    # :role:`target` -> `target`
    text = re.sub(r":(class|meth|func|attr|data|obj):`~?([^`]+)`", r"`\2`", text)
    # ``code`` -> `code`
    text = re.sub(r"``([^`]+)``", r"`\1`", text)
    return text


def format_docstring(obj):
    """Return cleaned docstring text, or empty string."""
    if not obj.docstring:
        return ""
    return clean_rst(obj.docstring.value.strip())


def first_sentence(obj):
    """Return the first sentence of the docstring."""
    doc = format_docstring(obj)
    if not doc:
        return ""
    # Take up to the first period followed by whitespace/end
    match = re.match(r"(.+?\.)\s", doc + " ")
    return match.group(1) if match else doc.split("\n")[0]


def format_parameter(param):
    """Format a single function parameter."""
    parts = [param.name]
    if param.annotation is not None:
        parts = [f"{param.name}: {param.annotation}"]
    if param.default is not None:
        default = str(param.default)
        if "<" in default and ">" in default:
            default = "..."
        parts[-1] += f" = {default}"
    return "".join(parts)


def format_signature(func):
    """Format a function signature from griffe data."""
    params = [
        format_parameter(p) for p in func.parameters if p.name not in ("self", "cls")
    ]
    return f"{func.name}({', '.join(params)})"


def render_function(out, func, heading="####"):
    """Render a function or method."""
    out.append(f"{heading} `{format_signature(func)}`")
    out.append("")
    doc = format_docstring(func)
    if doc:
        out.append(doc)
        out.append("")


def render_class(out, cls):
    """Render a class with its properties and methods."""
    out.append(f"### `{cls.name}`")
    out.append("")
    doc = format_docstring(cls)
    if doc:
        out.append(doc)
        out.append("")

    for member in cls.members.values():
        if member.name.startswith("_") and member.name != "__init__":
            continue
        try:
            if member.kind == griffe.Kind.ATTRIBUTE and member.labels:
                if "property" in member.labels:
                    out.append(f"#### `{member.name}`")
                    out.append("")
                    pdoc = format_docstring(member)
                    if pdoc:
                        out.append(pdoc)
                        out.append("")
            elif member.kind == griffe.Kind.FUNCTION:
                render_function(out, member)
        except griffe.AliasResolutionError:
            continue


def get_module_members(mod):
    """Get classes and functions defined in a module (not imports)."""
    classes = []
    functions = []
    for member in mod.members.values():
        if member.name.startswith("_") or isinstance(member, griffe.Alias):
            continue
        try:
            if member.kind == griffe.Kind.CLASS:
                classes.append(member)
            elif member.kind == griffe.Kind.FUNCTION:
                functions.append(member)
        except griffe.AliasResolutionError:
            continue
    return classes, functions


def render_module_page(mod):
    """Render a full module page."""
    out = [f"# `{mod.name}`", "", GENERATED_NOTICE, ""]

    doc = format_docstring(mod)
    if doc:
        out.append(doc)
        out.append("")

    classes, functions = get_module_members(mod)

    for cls in classes:
        render_class(out, cls)

    if functions:
        if classes:
            out.append("### Module Functions")
            out.append("")
        for func in functions:
            render_function(out, func)

    return "\n".join(out).rstrip() + "\n"


def render_index(modules):
    """Render the index page with module listing."""
    out = [
        "# Python Library Reference (`pyishlib`)",
        "",
        GENERATED_NOTICE,
        "",
    ]

    for mod in modules:
        classes, functions = get_module_members(mod)
        summary = first_sentence(mod)

        out.append(f"## [`{mod.name}`]({mod.name}.md)")
        out.append("")
        if summary:
            out.append(summary)
            out.append("")

        if classes:
            for cls in classes:
                cls_summary = first_sentence(cls)
                line = f"- `{cls.name}`"
                if cls_summary:
                    line += f" -- {cls_summary}"
                out.append(line)
            out.append("")

        if functions:
            names = ", ".join(f"`{f.name}`" for f in functions)
            out.append(f"Functions: {names}")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def main(out_dir=None):
    """Generate the Python API reference markdown.

    Args:
        out_dir: Override output directory. Defaults to ``docs/pyishlib/``
                 relative to the repository root.
    """
    output_dir = out_dir or OUTPUT_DIR

    pkg = griffe.load("pyishlib", search_paths=[SRC_DIR])

    modules = sorted(
        (m for m in pkg.members.values() if m.kind == griffe.Kind.MODULE),
        key=lambda m: m.name,
    )

    os.makedirs(output_dir, exist_ok=True)

    # Remove stale module files
    current_names = {m.name for m in modules}
    for existing in os.listdir(output_dir):
        if existing == "index.md":
            continue
        if not existing.endswith(".md"):
            continue
        stem = existing[: -len(".md")]
        if stem not in current_names:
            os.remove(os.path.join(output_dir, existing))

    # Write index
    index_path = os.path.join(output_dir, "index.md")
    with open(index_path, "w", encoding="utf-8") as fh:
        fh.write(render_index(modules))

    # Write per-module pages
    for mod in modules:
        mod_path = os.path.join(output_dir, f"{mod.name}.md")
        with open(mod_path, "w", encoding="utf-8") as fh:
            fh.write(render_module_page(mod))

    print(f"Generated {len(modules)} module pages + index in {output_dir}/")


def cli_main():
    """CLI entry point: parse arguments and call :func:`main`."""
    import argparse

    parser = argparse.ArgumentParser(description="Generate pyishlib API docs")
    parser.add_argument(
        "--out-dir",
        default=None,
        help=f"Output directory (default: {OUTPUT_DIR})",
    )
    args = parser.parse_args()
    main(out_dir=args.out_dir)


if __name__ == "__main__":
    cli_main()
