commands:
  type: list
  schema:
    type: string
cargo_package:
  type: dict
  keysrules:
    type: string
  valuesrules:
    type: string
apt_package:
  type: dict
  keysrules:
    type: string
  valuesrules:
    type: string
